name: clliaa
channels:
  - defaults
dependencies:
  - libgcc-ng=8.2
  - libsodium=1.0
  - libstdcxx-ng=8.2
  - ncurses=6.1
  - pip
  - python=3
  - readline=7
  - setuptools
  - tk=8.6
  - pip:
    - backcall==0.1.0
    - click==7.0
    - cycler==0.10.0
    - cython==0.29.7
    - decorator==4.4.0
    - docopt==0.6.2
    - flask==0.12.4
    - flask-compress==1.4.0
    - flask-socketio==2.9.6
    - future==0.17.1
    - gdbgui==0.13.1.2
    - gevent==1.4.0
    - greenlet==0.4.15
    - gym==0.12.4
    - gymz==0.0.3
    - ipython-genutils==0.2.0
    - itsdangerous==1.1.0
    - jedi==0.14.1
    - jinja2==2.10.1
    - kiwisolver==1.1.0
    - lxml==4.3.3
    - markupsafe==1.1.1
    - matplotlib==3.1.0
    - mpi4py==3.0.1
    - numpy==1.16.3
    - parso==0.5.1
    - pexpect==4.7.0
    - prompt-toolkit==2.0.9
    - pygdbmi==0.9.0.1
    - pyglet==1.3.2
    - pygments==2.4.2
    - pyparsing==2.4.0
    - python-engineio==3.5.2
    - python-socketio==4.0.2
    - pyzmq==18.0.1
    - scipy==1.3.0
    - six==1.12.0
    - svgutils==0.3.1
    - traitlets==4.3.2
    - wcwidth==0.1.8
    - werkzeug==0.15.4
